version: 1

formatters:
  precise:
    
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: /var/log/matrix/event-persister-10-worker.log
    when: midnight
    backupCount: 3  # Does not include the current log file.
    encoding: utf8

  console:
    class: logging.StreamHandler
    formatter: precise



loggers:
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO


root:
    level: INFO


    handlers: [file]


disable_existing_loggers: false
